version: '3.8'

services:
  # 1. PostgreSQL Database
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. PHP-FPM (Serviço de backend - Laravel)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  # 3. Nginx Web Server
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # 4. Node/React (Serviço de frontend)
  # 4. Node/React (Serviço de frontend)
  frontend:
    image: node:20-alpine  # <--- CORREÇÃO AQUI
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: tail -F /dev/null

volumes:
  dbdata: